server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与 seata-server 中对应
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:               jdbc:mysql://172.18.0.4:3306/seata_account?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username:          root
    password:          mysqldocker

feign:
  hystrix:
    enabled: false

mybatis:
  mapperLocations: classpath:mapper/*.xml
  
debug: true