server:
  port: 8080

spring:
  application:
    name: consul-consumerconsul-order
  cloud:
    consul:
      host: 169.0.0.2
      port: 8500
      discovery:
        service-name: ${spring.application.name}
      